### ISSUE TITLE
_02_munge_chains.py crashes due to "date" keyError.

### ISSUE THREAD

**Issue by Mdraugelis** [pennsignals/chime_sims#51]
Only crashes for PAH.  I inspected the _ts.csv file and parameter file and didn't notice any issues.

``` ~/anaconda3/bin/python3 _02_munge_chains.py -o output/2020_04_24_16_51_24_PAH/ -d 100 -pc -P 'PAH'
Output directory: output/2020_04_24_16_51_24_PAH/
Traceback (most recent call last):
  File "/home/datascience/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_02_munge_chains.py", line 428, in <module>
    main()
  File "_02_munge_chains.py", line 306, in main
    first_day = census_ts["date"].values[0]
  File "/home/datascience/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/datascience/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'date'
```

**Comment by Hanisha13** [comment]
@Mdraugelis Might be crashing due to zero vents.

**Comment by Mdraugelis** [comment]
crashed due to type.  on the date column.  I've fixed, tested and loaded to master.
